@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 25 21:08:40 +0500 2024
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim RISCV_Single_Cycle_Processor_Top_tb_behav -key {Behavioral:sim_1:Functional:RISCV_Single_Cycle_Processor_Top_tb} -tclbatch RISCV_Single_Cycle_Processor_Top_tb.tcl -view C:/Users/abu.bakar/Documents/RISC_V_Single_Cycle_Core/project_1/RISCV_Single_Cycle_Processor_Top_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
